### ISSUE TITLE
"My list" display botched after adding items and switching to portait-mode

### ISSUE THREAD

**Issue by matz-e** [andrewbrey/netflix-tweaked#9] opened 2018-07-15 08:19 UTC
**Describe the bug**
After adding several items to 'My List', Netflix decided that it should show up in a portait-oriented mode rather than landscape-oriented. The new mode is displayed messed up (see attached screenshot).

**To Reproduce**
1. Go to home screen
2. Add something to 'My List' 
3. Scroll up to 'My List'
4. See if 'My List' has switched to some portait-oriented view
    * if not, go to (2)

**Expected behavior**
'My List' to display properly

**Screenshots**
Dispaly after adding some movies to 'My List':

![my_list](https://user-images.githubusercontent.com/2151261/42731971-62a5d60a-8818-11e8-8c64-ffdf0cde036c.png)

**Desktop (please complete the following information):**
 - OS: Mac OS 10.13.5
 - Browser: Firefox
 - Version 62.0b5

**Comment by andrewbrey** [comment] 2018-07-16 00:17
@matz-e I have a couple hypotheses what might be happening here, but I am not able to reproduce this in either Chrome or Firefox locally, so it's hard to confirm. Is there any way you could reproduce this behavior then attach the page source as it exists at the time of experiencing this? It should suffice to `right click` and hit `View Page Source` on the home screen once this issue presents itself.

**Comment by andrewbrey** [comment] 2018-07-16 17:08
@matz-e I just pushed out an update (v1.0.10) that I _think_ will resolve this issue for you, though again I could never reproduce it so it's hard to know for sure. Could you give it a test and see? Also, I just want to point out that the "tall thumbnails" for Netflix Originals are not a result of the extension, that's just how Netflix _sometimes_ chooses to display the Netflix Original content (to visually prioritize it).

**Comment by andrewbrey** [comment] 2018-07-16 17:10
Should be fixed by a526383.

**Closed by andrewbrey** 2018-07-16 17:10 UTC
Labels: Firefox, bug

**Comment by matz-e** [comment] 2018-07-17 05:04
@andrewbrey Thanks, that fixed it for me! Sorry, I hadn't gotten around to providing you a snapshot of the site source. Netflix seemed to push the tall thumbnails every 5-6 additions to "My List", which I've now populated quite a bit without the list switching to tall thumbnails :)
