### ISSUE TITLE
Firefox: Previews are back

### ISSUE THREAD

**Issue by Eetheart** [andrewbrey/netflix-tweaked#13] opened 2018-11-17 18:39 UTC
(For some reason I couldn't leave a review/note on the Firefox Add-On page, so here it is)

Worked fine for months until now. Previews are back, but the list and continue watching categories remain at the top, directly under the previews.

**Comment by andrewbrey** [comment] 2018-11-19 03:00
Gah! I knew at the outset that this would be an arms race with Netflix to suppress the auto-play, but I did hope it would take longer than a couple months for it to break ☹

I have really limited time to devote to issues on this repository for right now, but I'll try to get to it as soon as possible - thanks for the issue report!

**Comment by andrewbrey** [comment] 2019-02-26 08:51
This is a duplicate of #15, so I'll close this in favor of the other issue.

**Closed by andrewbrey** 2019-02-26 08:51 UTC
Labels: Firefox, bug, help wanted
